apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service # name of service just to identify by master
spec:           # specification for below to connect
  type: ClusterIP #its is now for cluster ip service instead of nodePort
  selector:   # this selector is used to match the name with whom it is going to associate and provide service to other objet in order to connect communicate with this pod/object
    component: web # name should be same as deployment pod or other object associated with for providing commincation network service
  ports:
    - port: 3000   # this port is for other objects running in kubes cluster and want to coonnet with the pod with this ervice associated with for provideing network communcaiton
      targetPort: 3000  # this port is for establish the network connection with the pod object with want to commincaute and set up channel with other objets in cluster with this object